name: javascript-test-runner / format

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-26.04
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0

      - name: Use Node.js LTS (20.x)
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e
        with:
          node-version: 20.x

      - name: Enable pnpm
        run: |
          corepack enable pnpm
          corepack pnpm -v

      - name: 'Verify formatting of all files'
        run: ./bin/check-formatting.sh
